# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def share_pods
  pod 'MaterialComponents/TextControls+FilledTextAreas'
  pod 'MaterialComponents/TextControls+FilledTextFields'
  pod 'TrueTime'
  pod "GSKStretchyHeaderView"
  pod 'YLProgressBar'
end

def use_flipper
  flipperkit_version = '0.175.0'
  flipper_configurations = ['Debug']
  pod 'FlipperKit', '~>' + flipperkit_version, :configurations => flipper_configurations
  pod 'FlipperKit/FlipperKitLayoutPlugin', '~>' + flipperkit_version, :configurations => flipper_configurations
  pod 'FlipperKit/SKIOSNetworkPlugin', '~>' + flipperkit_version, :configurations => flipper_configurations
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', '~>' + flipperkit_version, :configurations => flipper_configurations
  # ...unfortunately at this time that means you'll need to explicitly mark
  # transitive dependencies as being for debug build only as well:
  pod 'Flipper-DoubleConversion', :configurations => flipper_configurations
  pod 'Flipper-Folly', :configurations => flipper_configurations
  pod 'Flipper-Glog', :configurations => flipper_configurations
  pod 'Flipper-PeerTalk', :configurations => flipper_configurations
  pod 'CocoaLibEvent', :configurations => flipper_configurations
  pod 'boost-for-react-native', :configurations => flipper_configurations
  pod 'libevent', :configuration => flipper_configurations
  pod 'boost-for-react-native', :configuration => flipper_configurations
  pod 'OpenSSL-Universal', :configuration => flipper_configurations

end

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  share_pods
  use_flipper
  
  # Pods for Example

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleUITests' do
    # Pods for testing
  end

  # If you use `use_frameworks!` in your Podfile,
    # uncomment the below $static_framework array and also
    # the pre_install section.  This will cause Flipper and
    # it's dependencies to be built as a static library and all other pods to
    # be dynamic.
    #
    # NOTE Doing this may lead to a broken build if any of these are also
    #      transitive dependencies of other dependencies and are expected
    #      to be built as frameworks.
    #
 $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly', 'Flipper-DoubleConversion',
      'Flipper-Glog', 'Flipper-PeerTalk',
      'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native', 'Flipper-Fmt']

  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
        if $static_framework.include?(pod.name)
          def pod.build_type;
            Pod::BuildType.static_library
          end
        end
      end
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.1'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
